# Generated by Django 5.2 on 2025-06-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار تخفیف (تومان)')),
                ('percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد تخفیف')),
                ('expiration_date', models.DateField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'db_table': 'discount_codes',
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_at', models.DateTimeField(auto_now_add=True, verbose_name='استفاده شده در تاریخ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت کرده؟')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Discount Code User',
                'verbose_name_plural': 'Discount Code Users',
                'db_table': 'discount_code_users',
                'unique_together': {('user', 'discount_code')},
            },
        ),
    ]
