# Generated by Django 5.2 on 2025-05-02 17:44

import core.media_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=50, verbose_name='عنوان در URL')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در URL')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=50, verbose_name='عنوان در URL')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان خدمت')),
                ('url_title', models.CharField(max_length=120, verbose_name='عنوان خدمت در URL')),
                ('slug', models.SlugField(blank=True, default='', max_length=120, unique=True)),
                ('description', models.TextField(max_length=800, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است ؟')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category', verbose_name='دسته بندی')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.profession', verbose_name='صنف')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.provider', verbose_name='ارائه دهنده')),
                ('tags', models.ManyToManyField(related_name='services', to='services.tag', verbose_name='تگ / تگ ها')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت هر عدد')),
                ('unit_description', models.CharField(max_length=80, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(verbose_name='آدرس فایل')),
                ('type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو')], max_length=10, verbose_name='نوع مدیا')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یک\u200cشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه'), (6, 'جمعه')], verbose_name='روز های هفته')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است؟')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='ظرفیت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='services.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'unique_together': {('service', 'weekday')},
            },
        ),
    ]
