# Generated by Django 5.2 on 2025-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_name_remove_province_name_city_name_en_and_more'),
        ('services', '0002_alter_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='locations',
            field=models.ManyToManyField(related_name='services', to='locations.city', verbose_name='شهر های قابل ارائه برای خدمات'),
        ),
    ]
