# Generated by Django 5.2 on 2025-05-04 09:30

import core.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر خدمت'),
        ),
    ]
