# Generated by Django 5.2 on 2025-05-04 09:45

import services.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=services.models.service.get_image_upload_to, verbose_name='تصویر خدمت'),
        ),
    ]
