# Generated by Django 5.2 on 2025-05-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_special',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ویژه است؟'),
        ),
    ]
