# Generated by Django 5.2 on 2025-05-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_is_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='is_special',
            new_name='is_unique',
        ),
    ]
