# Generated by Django 5.2 on 2025-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_is_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='ویژه است؟'),
        ),
    ]
