# Generated by Django 5.2 on 2025-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(default='none', max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
