# Generated by Django 5.2 on 2025-05-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_provider_city_alter_provider_province'),
        ('locations', '0002_remove_city_name_remove_province_name_city_name_en_and_more'),
        ('services', '0010_category_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='کد خدمت'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='services_code_5c47ad_idx'),
        ),
    ]
