# Generated by Django 5.2 on 2025-05-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.platform', verbose_name='پلتفرم'),
        ),
    ]
