# Generated by Django 5.2 on 2025-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_category_parent_category_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='url_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='url_title',
        ),
    ]
