# Generated by Django 5.2 on 2025-05-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_profession_url_title_remove_service_url_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url_title',
        ),
    ]
