# Generated by Django 5.2 on 2025-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_service_slug_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profession',
        ),
        migrations.AddField(
            model_name='service',
            name='profession',
            field=models.ManyToManyField(related_name='services', to='services.profession', verbose_name='صنف'),
        ),
    ]
