# Generated by Django 5.2 on 2025-05-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_service_profession_service_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='unit_description',
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.option', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'Option Item',
                'verbose_name_plural': 'Option Items',
                'db_table': 'option_items',
            },
        ),
    ]
