# Generated by Django 5.2 on 2025-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_option_unit_description_optionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='قیمت هر عدد'),
        ),
    ]
