# Generated by Django 5.2 on 2025-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_optionitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='platform_link',
            field=models.URLField(max_length=120, null=True, verbose_name='لینک بستر تبلیغاتی'),
        ),
    ]
