# Generated by Django 5.2 on 2025-05-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_service_platform_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر / دستگاه')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='صفحه ارجاع\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='خدمت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Service Visit',
                'verbose_name_plural': 'Service Visits',
                'db_table': 'service_visits',
            },
        ),
    ]
