# Generated by Django 5.2 on 2025-05-21 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_servicevisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceVisit',
            new_name='Visit',
        ),
    ]
