# Generated by Django 5.2 on 2025-05-21 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_favorite_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='services.service', verbose_name='خدمت'),
        ),
    ]
