# Generated by Django 5.2 on 2025-05-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_favorite_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='services.service', verbose_name='خدمت'),
        ),
    ]
