# Generated by Django 5.2 on 2025-06-07 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_visit_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='ServiceVisit',
        ),
        migrations.AlterModelOptions(
            name='servicevisit',
            options={},
        ),
    ]
