# Generated by Django 5.2 on 2025-06-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_rename_visit_servicevisit_alter_servicevisit_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicevisit',
            table='services_visits',
        ),
    ]
