# Generated by Django 5.2 on 2025-06-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_alter_servicevisit_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='ServiceTag',
        ),
        migrations.AlterModelTable(
            name='servicetag',
            table=None,
        ),
    ]
