# Generated by Django 5.2 on 2025-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_rename_tag_servicetag_alter_servicetag_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetag',
            options={'verbose_name': 'Service Tag', 'verbose_name_plural': 'Service Tags'},
        ),
    ]
