# Generated by Django 5.2 on 2025-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_alter_servicetag_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
    ]
