# Generated by Django 5.2 on 2025-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_alter_schedule_unique_together_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
