# Generated by Django 5.2 on 2025-07-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_alter_schedule_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'option')},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.option', verbose_name='نوع تبلیغ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='خریدار'),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
    ]
