# Generated by Django 5.2 on 2025-07-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_alter_reservation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.schedule', verbose_name='زمان\u200cبندی رزرو'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'schedule', 'option')},
        ),
    ]
