# Generated by Django 5.2 on 2025-07-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reserve', 'verbose_name_plural': 'Reserves'},
        ),
    ]
