# Generated by Django 5.2 on 2025-08-13 09:47

import core.media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر خدمت'),
        ),
    ]
