# Generated by Django 5.2 on 2025-11-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform_link',
            field=models.CharField(max_length=120, null=True, verbose_name='لینک بستر تبلیغاتی'),
        ),
    ]
