# Generated by Django 5.2 on 2025-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_alter_service_platform_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform_link',
            field=models.CharField(max_length=80, null=True, verbose_name='لینک بستر تبلیغاتی'),
        ),
    ]
