# Generated by Django 5.2 on 2025-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_alter_service_platform_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='platform_link',
            field=models.CharField(default=1, max_length=80, verbose_name='لینک بستر تبلیغاتی'),
            preserve_default=False,
        ),
    ]
