# Generated by Django 5.2 on 2025-04-27 19:55

import accounts.managers
import core.media_path
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='نام کاربری')),
                ('slug', models.SlugField(blank=True, default='', max_length=60, unique=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('province', models.CharField(max_length=100, verbose_name='استان محل سکونت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل سکونت')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر پروفایل')),
                ('iban_number', models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='شماره شبا باید ۲۴ رقم باشد.', regex='^\\d{24}$')], verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='شماره کارت باید ۱۶ رقم باشد.', regex='^\\d{16}$')], verbose_name='شماره کارت')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر کارت ملی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('active', 'فعال'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
        ),
    ]
