# Generated by Django 5.2 on 2025-04-27 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر محل سکونت'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان محل سکونت'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
