# Generated by Django 5.2 on 2025-05-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_provider_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_create_time',
            new_name='otp_create_at',
        ),
    ]
