# Generated by Django 5.2 on 2025-05-01 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_create_time_user_otp_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='کد تایید باید دقیقا ۶ رقم عددی باشد.', regex='^\\d{6}$')], verbose_name='کد تایید'),
        ),
    ]
