# Generated by Django 5.2 on 2025-05-05 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_verified'),
        ('locations', '0002_remove_city_name_remove_province_name_city_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='شهر محل سکونت'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.province', verbose_name='استان محل سکونت'),
        ),
    ]
