# Generated by Django 5.2 on 2025-06-07 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_provider_city_alter_provider_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'انتخاب کنید...'), ('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='لطفا شماره موبایل خود را به درستی وارد کنید.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
