# Generated by Django 5.2 on 2025-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_gender_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده؟'),
        ),
    ]
