# Generated by Django 5.2 on 2025-08-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_provider_is_profile_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Provider Platform',
                'verbose_name_plural': 'Provider Platforms',
                'db_table': 'provider_platforms',
            },
        ),
    ]
