# Generated by Django 5.2 on 2025-08-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_providerplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerplatform',
            name='platform_name',
            field=models.CharField(max_length=50, verbose_name='نام پلتفرم'),
        ),
        migrations.AlterField(
            model_name='providerplatform',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='accounts.provider', verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='providerplatform',
            name='url',
            field=models.URLField(verbose_name='آدرس پلتفرم'),
        ),
    ]
