# Generated by Django 5.2 on 2025-08-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_providerplatform_platform_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerplatform',
            old_name='platform_name',
            new_name='name',
        ),
    ]
