# Generated by Django 5.2 on 2025-08-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_platform_name_providerplatform_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderPlatform',
        ),
    ]
