# Generated by Django 5.2 on 2025-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_providerplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
