# Generated by Django 5.2 on 2025-08-17 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_provider_instagram_url_provider_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ عضویت'),
            preserve_default=False,
        ),
    ]
