# Generated by Django 5.2 on 2025-08-19 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(default=3, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='شماره کارت باید ۱۶ رقم باشد.', regex='^\\d{16}$')], verbose_name='شماره کارت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba_number',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='شماره شبا باید ۲۴ رقم باشد.', regex='^\\d{24}$')], verbose_name='شماره شبا'),
        ),
    ]
