# Generated by Django 5.2 on 2025-08-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_bankaccount_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='iban_number',
        ),
    ]
