# Generated by Django 5.2 on 2025-08-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_bankaccount_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('prefix', models.CharField(max_length=6, unique=True)),
                ('logo', models.ImageField(upload_to='banks/')),
            ],
        ),
    ]
