# Generated by Django 5.2 on 2025-08-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bank', verbose_name='بانک'),
        ),
    ]
