# Generated by Django 5.2 on 2025-08-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
    ]
