# Generated by Django 5.2 on 2025-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_bank_options_alter_bank_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(upload_to='banks/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='prefix',
            field=models.CharField(max_length=6, unique=True, verbose_name='پیش شماره'),
        ),
    ]
