# Generated by Django 5.2 on 2025-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_bankaccount_is_default_alter_bank_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
