# Generated by Django 5.2 on 2025-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_otp_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
