# Generated by Django 5.2 on 2025-06-07 09:59

import core.media_path
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پست')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True)),
                ('image', models.ImageField(null=True, upload_to=core.media_path.get_image_upload_to, verbose_name='تصویر پست')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در تاریخ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است؟')),
                ('is_unique', models.BooleanField(default=False, verbose_name='ویژه است؟')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='BlogVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='مرورگر / دستگاه')),
                ('referer', models.URLField(blank=True, null=True, verbose_name='صفحه ارجاع\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='blog.post', verbose_name='پست')),
            ],
            options={
                'db_table': 'posts_visits',
            },
        ),
    ]
