# Generated by Django 5.2 on 2025-06-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, default='', max_length=35, unique=True)),
            ],
            options={
                'db_table': 'posts_tags',
            },
        ),
    ]
