# Generated by Django 5.2 on 2025-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={'verbose_name': 'Post Tag', 'verbose_name_plural': 'Post Tags'},
        ),
    ]
