# Generated by Django 5.2 on 2025-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.posttag', verbose_name='تگ / تگ ها'),
        ),
        migrations.AlterModelTable(
            name='posttag',
            table=None,
        ),
    ]
