# Generated by Django 5.2 on 2025-06-11 10:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags_alter_posttag_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='محتوای متن'),
        ),
    ]
