# Generated by Django 5.2 on 2025-05-13 09:12

import core.media_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'Footer Box',
                'verbose_name_plural': 'Footer Boxes',
                'db_table': 'footer_boxes',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=35, verbose_name='عنوان')),
                ('logo_1', models.ImageField(upload_to=core.media_path.get_image_upload_to, verbose_name='لوگو ۱')),
                ('logo_2', models.ImageField(upload_to=core.media_path.get_image_upload_to, verbose_name='لوگو ۲')),
                ('transparent_logo', models.ImageField(upload_to=core.media_path.get_image_upload_to, verbose_name='لوگو شفاف')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل وب سایت')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس وب سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='لینک')),
                ('footer_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.footerbox', verbose_name='باکس')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'db_table': 'footer_links',
            },
        ),
    ]
