# Generated by Django 5.2 on 2025-05-14 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0014_service_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'Footer Box',
                'verbose_name_plural': 'Footer Boxes',
                'db_table': 'footer_boxes',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=35, verbose_name='عنوان')),
                ('logo_1', models.ImageField(upload_to='site_setting/logo_1', verbose_name='لوگو ۱')),
                ('logo_2', models.ImageField(upload_to='site_setting/logo_2', verbose_name='لوگو ۲')),
                ('transparent_logo', models.ImageField(upload_to='site_setting/transparent_logo', verbose_name='لوگو شفاف')),
                ('footer_text', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل وب سایت')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس وب سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('is_main', models.BooleanField(default=False, unique=True, verbose_name='تنظیمات اصلی؟')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='لینک')),
                ('footer_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.footerbox', verbose_name='باکس')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'db_table': 'footer_links',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('url', models.CharField(blank=True, max_length=75, null=True, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='services.platform')),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='عنوان')),
                ('url', models.URLField(max_length=75, verbose_name='آدرس')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sitesetting', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('url', models.CharField(blank=True, max_length=75, null=True, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='config.maincategory', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'Category Item',
                'verbose_name_plural': 'Category Items',
                'db_table': 'category_items',
                'unique_together': {('main_category', 'title')},
            },
        ),
    ]
