# Generated by Django 5.2 on 2025-05-14 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('services', '0014_service_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_categories', to='services.platform', verbose_name='پلتفرم'),
        ),
    ]
