# Generated by Django 5.2 on 2025-05-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'db_table': 'main_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='config.maincategory', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'Category Item',
                'verbose_name_plural': 'Category Items',
                'db_table': 'category_items',
                'ordering': ['order'],
                'unique_together': {('main_category', 'title')},
            },
        ),
    ]
