# Generated by Django 5.2 on 2025-05-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_maincategory_categoryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'verbose_name': 'Category Item', 'verbose_name_plural': 'Category Items'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Main Category', 'verbose_name_plural': 'Main Categories'},
        ),
    ]
