# Generated by Django 5.2 on 2025-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_maincategory_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='title',
            field=models.CharField(max_length=45, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='url',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='footerbox',
            name='title',
            field=models.CharField(max_length=35, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.URLField(max_length=90, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=45, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='url',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='title',
            field=models.CharField(max_length=35, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(max_length=90, verbose_name='آدرس'),
        ),
    ]
