# Generated by Django 5.2 on 2025-05-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_categoryitem_title_alter_categoryitem_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footer_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='config.footerbox', verbose_name='باکس'),
        ),
    ]
