# Generated by Django 5.2 on 2025-05-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_categoryitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('url', models.URLField(max_length=255, verbose_name='آدرس')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sitesetting', verbose_name='تنظیمات')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
            },
        ),
    ]
