# Generated by Django 5.2 on 2025-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_categoryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_main',
            field=models.BooleanField(default=False, unique=True, verbose_name='تنظیمات اصلی؟'),
        ),
    ]
