# Generated by Django 5.2 on 2025-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_footerlink_footer_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='min_withdraw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حداقل برداشت'),
        ),
    ]
