# Generated by Django 5.2 on 2025-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='title',
            field=models.CharField(max_length=25, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(max_length=75, verbose_name='آدرس'),
        ),
    ]
