# Generated by Django 5.2 on 2025-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_sitesetting_logo_1_alter_sitesetting_logo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_1',
            field=models.ImageField(upload_to='site_setting/logo_1', verbose_name='لوگو ۱'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_2',
            field=models.ImageField(upload_to='site_setting/logo_2', verbose_name='لوگو ۲'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='transparent_logo',
            field=models.ImageField(upload_to='site_setting/transparent_logo', verbose_name='لوگو شفاف'),
        ),
    ]
