# Generated by Django 5.2 on 2025-08-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_sitesetting_min_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='min_withdraw',
        ),
    ]
