# Generated by Django 5.2 on 2025-10-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_remove_sitesetting_min_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
    ]
