# Generated by Django 5.2 on 2025-10-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_sitesetting_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دفتر مرکزی'),
        ),
    ]
