# Generated by Django 5.2 on 2025-05-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0023_service_platform_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True, verbose_name='Title')),
                ('text', models.TextField(max_length=450, verbose_name='متن')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=8, verbose_name='وضعیت')),
                ('recommendation', models.CharField(blank=True, choices=[('good', 'میکنم'), ('bad', 'نمیکنم')], max_length=7, null=True, verbose_name='پیشنهاد کاربر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.servicereview')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service', verbose_name='خدمت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'db_table': 'service_reviews',
            },
        ),
        migrations.CreateModel(
            name='ServiceReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'پسندیدم'), ('dislike', 'نپسندیدم')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reviews.servicereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Review Reaction',
                'verbose_name_plural': 'Service Review Reactions',
                'db_table': 'service_review_reactions',
                'unique_together': {('user', 'review')},
            },
        ),
    ]
