# Generated by Django 5.2 on 2025-05-18 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.servicereview', verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='servicereviewreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='servicereviewreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'پسندیدم'), ('dislike', 'نپسندیدم')], max_length=7, verbose_name='ری اکشن'),
        ),
        migrations.AlterField(
            model_name='servicereviewreaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reviews.servicereview', verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='servicereviewreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
