# Generated by Django 5.2 on 2025-05-18 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_servicereview_parent_alter_servicereview_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereview',
            name='create_date',
        ),
        migrations.AddField(
            model_name='servicereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
