# Generated by Django 5.2 on 2025-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_servicereview_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=8, verbose_name='وضعیت'),
        ),
    ]
