# Generated by Django 5.2 on 2025-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_servicereview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereview',
            name='title',
            field=models.CharField(max_length=75, verbose_name='عنوان'),
        ),
    ]
