# Generated by Django 5.2 on 2025-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_servicereview_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicereview',
            table='services_reviews',
        ),
        migrations.AlterModelTable(
            name='servicereviewreaction',
            table='services_review_reactions',
        ),
    ]
