# Generated by Django 5.2 on 2025-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('banner', 'بنر صفحه اصلی'), ('brand', 'برندها'), ('gateway', 'درگاه پرداخت'), ('category', 'دسته\u200cبندی\u200cها'), ('header_link', 'لینک های هدر'), ('other', 'سایر (هدر)')], max_length=50, verbose_name='بخش مربوطه')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_items/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک ارجاعی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'db_table': 'media_item',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
