# Generated by Django 5.2 on 2025-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='image',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='media_items/', verbose_name='عکس دسکتاپ'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='media_items/', verbose_name='عکس موبایل'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='section',
            field=models.CharField(choices=[('home_banner', 'بنر صفحه اصلی'), ('home_gif', 'گیف صفحه اصلی'), ('brand', 'برندها'), ('payment', 'درگاه پرداخت'), ('category', 'دسته\u200cبندی\u200cها'), ('header_link', 'لینک های هدر'), ('other', 'سایر (هدر)')], max_length=50, verbose_name='بخش مربوطه'),
        ),
    ]
