# Generated by Django 5.2 on 2025-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_mediaitem_image_mediaitem_image_desktop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='payment_tag',
            field=models.TextField(blank=True, help_text='تگ کامل <a> ارائه\u200cشده توسط درگاه پرداخت را اینجا قرار دهید.', null=True, verbose_name='کد HTML درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image_desktop',
            field=models.ImageField(blank=True, help_text='ابعاد پیشنهادی بسته به بخش مربوطه:\n• بنر صفحه اصلی: ۲۸۸۰×۶۰۰ پیکسل\n• گیف صفحه اصلی: ۲۸۰۰×۱۰۰ پیکسل\n• پلتفرم ها و دسته\u200cبندی\u200cها: دلخواه', null=True, upload_to='media_items/', verbose_name='عکس دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='ابعاد پیشنهادی بسته به بخش مربوطه:\n• بنر صفحه اصلی: ۲۸۸۰×۶۰۰ پیکسل\n• گیف صفحه اصلی: ۲۸۰۰×۱۰۰ پیکسل\n• پلتفرم ها و دسته\u200cبندی\u200cها: دلخواه', null=True, upload_to='media_items/', verbose_name='عکس موبایل'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='section',
            field=models.CharField(choices=[('home_banner', 'بنر صفحه اصلی'), ('home_gif', 'گیف صفحه اصلی'), ('platform', 'پلتفرم ها'), ('payment', 'درگاه پرداخت'), ('category', 'دسته\u200cبندی\u200cها'), ('header_link', 'لینک های هدر'), ('other', 'سایر (هدر)')], max_length=50, verbose_name='بخش مربوطه'),
        ),
    ]
