# Generated by Django 5.2 on 2025-10-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mediaitem_payment_tag_alter_mediaitem_image_desktop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Asan Tab | آسان تب', max_length=255)),
                ('meta_description', models.TextField(default='پلتفرم رزرو و ارائه خدمات آنلاین آسان تب')),
                ('meta_keywords', models.CharField(default='آسان تب, خدمات, رزرو, تبلیغات ارزان', max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('robots_txt', models.TextField(blank=True, null=True)),
                ('canonical_base', models.URLField(default='https://asantab.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global SEO',
                'verbose_name_plural': 'Global SEO Settings',
                'db_table': 'global_seo',
            },
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='section',
            field=models.CharField(choices=[('upper_banner', 'بنر بالای صفحه'), ('home_gif', 'گیف صفحه اصلی'), ('body_banner', 'بنر وسط صفحه'), ('header_link', 'لینک های هدر'), ('platform', 'پلتفرم ها'), ('category', 'دسته\u200cبندی\u200cها'), ('payment', 'درگاه پرداخت'), ('other', 'سایر (هدر)')], max_length=50, verbose_name='بخش مربوطه'),
        ),
    ]
