# Generated by Django 5.2 on 2025-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_globalseo_alter_mediaitem_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('faq', 'سوالات متداول'), ('policy', 'قوانین و مقررات')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Info Item',
                'verbose_name_plural': 'Info Items',
                'db_table': 'info_item',
                'ordering': ['id'],
            },
        ),
    ]
