# Generated by Django 5.2 on 2025-10-23 09:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_infoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoitem',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='محتوای متن'),
        ),
    ]
