# Generated by Django 5.2 on 2025-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_infoitem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoitem',
            name='type',
            field=models.CharField(choices=[('faq', 'سوالات متداول'), ('rules', 'قوانین و مقررات')], max_length=10),
        ),
    ]
