# Generated by Django 5.2 on 2025-08-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر'), ('staff', 'کارشناس'), ('provider', 'فروشنده'), ('user', 'کاربر')], max_length=20, verbose_name='نقش')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی آزاد')),
                ('frozen_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='موجودی معلق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'شارژ'), ('withdraw', 'برداشت'), ('freeze', 'مسدودسازی'), ('release', 'آزادسازی'), ('transfer', 'انتقال'), ('commission', 'کمیسیون')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='wallet.wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
