# Generated by Django 5.2 on 2025-08-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_bankaccount_is_default_alter_bank_logo_and_more'),
        ('wallet', '0002_alter_wallet_options_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('sheba_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='accounts.bankaccount', verbose_name='حساب بانکی')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'withdrawal_requests',
                'ordering': ['created_at'],
            },
        ),
    ]
