# Generated by Django 5.2 on 2025-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='نام درگاه')),
                ('merchant_id', models.CharField(max_length=120, verbose_name='شناسه فروشنده')),
                ('callback_url', models.URLField(verbose_name='آدرس بازگشت بعد از پرداخت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال است؟')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateway',
                'db_table': 'payment_gateway',
            },
        ),
    ]
