# Generated by Django 5.2 on 2025-08-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_paymentgateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع پرداخت (PSP)')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه درخواست (Authority)')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری بانکی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده در')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallet.paymentgateway', verbose_name='درگاه پرداخت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'db_table': 'deposit_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
