# Generated by Django 5.2 on 2025-08-25 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_depositrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='merchant_id',
            field=models.CharField(max_length=120, unique=True, verbose_name='شناسه فروشنده'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'شارژ'), ('withdrawal', 'برداشت'), ('refund', 'بازگشت')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع PSP')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه درخواست (Authority)')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری بانکی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.paymentgateway', verbose_name='درگاه پرداخت')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
