# Generated by Django 5.2 on 2025-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_paymentgateway_merchant_id_paymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'کارشناس'), ('provider', 'فروشنده'), ('user', 'کاربر')], max_length=20, verbose_name='نقش')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد کمیسیون')),
                ('fixed_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ ثابت')),
                ('min_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حداقل مبلغ تراکنش برای اعمال')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='حداکثر مبلغ تراکنش برای اعمال')),
            ],
            options={
                'verbose_name': 'Commission Rule',
                'verbose_name_plural': 'Commission Rules',
                'db_table': 'commission_rules',
            },
        ),
    ]
