# Generated by Django 5.2 on 2025-08-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_commissionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_wallet', to='wallet.wallet', verbose_name='کیف پول سایت')),
            ],
            options={
                'verbose_name': 'Site Wallet',
                'verbose_name_plural': 'Site Wallets',
                'db_table': 'site_wallet',
            },
        ),
    ]
