# Generated by Django 5.2 on 2025-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_sitewallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentgateway',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='fixed_amount',
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع PSP'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
