# Generated by Django 5.2 on 2025-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_active_paymentgateway_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='secret_code',
            field=models.CharField(default=123, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری'),
        ),
    ]
