# Generated by Django 5.2 on 2025-09-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_wallet_secret_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='secret_code',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
