# Generated by Django 5.2 on 2025-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_secret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ'), ('withdraw', 'برداشت'), ('freeze', 'مسدودسازی'), ('release', 'آزادسازی'), ('transfer', 'کسر از حساب'), ('commission', 'کمیسیون')], max_length=20),
        ),
    ]
