# Generated by Django 5.2 on 2025-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ / واریز'), ('withdraw', 'برداشت'), ('freeze', 'مسدودسازی'), ('release', 'آزادسازی'), ('transfer', 'کسر از حساب'), ('commission', 'کمیسیون')], max_length=20),
        ),
    ]
