# Generated by Django 5.2 on 2025-09-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrule',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='role',
        ),
    ]
