# Generated by Django 5.2 on 2025-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_remove_commissionrule_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrule',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='commissionrule',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='title',
            field=models.CharField(default='default', max_length=100, verbose_name='عنوان کارمزد'),
            preserve_default=False,
        ),
    ]
