# Generated by Django 5.2 on 2025-09-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_withdrawalrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='tracking_code',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
