# Generated by Django 5.2 on 2025-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.RemoveField(
            model_name='province',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام شهر به انگلیسی'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام شهر به فارسی'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام استان به انگلیسی'),
        ),
        migrations.AddField(
            model_name='province',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='نام استان به فارسی'),
        ),
    ]
