# Generated by Django 5.2 on 2025-09-24 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='نام دپارتمان')),
            ],
            options={
                'verbose_name': 'Ticket Department',
                'verbose_name_plural': 'Ticket Departments',
                'db_table': 'ticket_departments',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع تیکت')),
                ('status', models.CharField(choices=[('unsubmitted', 'ثبت نهایی نشده'), ('open', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketdepartment', verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_agent', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('departments', models.ManyToManyField(related_name='agents', to='tickets.ticketdepartment', verbose_name='دپارتمان\u200cها')),
            ],
            options={
                'verbose_name': 'Support Agent',
                'verbose_name_plural': 'Support Agents',
                'db_table': 'support_agents',
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
