# Generated by Django 5.2 on 2025-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketdepartment_ticket_supportagent_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='شناسه پیگیری'),
        ),
    ]
