# Generated by Django 5.2 on 2025-06-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
