# Generated by Django 5.2 on 2025-06-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_gender_alter_user_phone_number'),
        ('orders', '0003_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to='accounts.provider', verbose_name='ارائه دهنده'),
        ),
    ]
