# Generated by Django 5.2 on 2025-07-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_provider'),
        ('services', '0034_alter_servicetag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.schedule', verbose_name='تاریخ رزرو'),
        ),
    ]
