# Generated by Django 5.2 on 2025-07-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_schedule'),
        ('services', '0036_alter_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='schedule',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.reservation', verbose_name='تاریخ رزرو'),
        ),
    ]
