# Generated by Django 5.2 on 2025-07-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_schedule_orderitem_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='reserve',
        ),
    ]
