# Generated by Django 5.2 on 2025-07-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_reserve'),
        ('services', '0038_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.schedule', verbose_name='تاریخ رزرو'),
        ),
    ]
