# Generated by Django 5.2 on 2025-07-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_options_remove_order_created_at_and_more'),
        ('services', '0039_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.option', verbose_name='آپشن انتخابی'),
        ),
    ]
