# Generated by Django 5.2 on 2025-09-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_bankaccount_is_default_alter_bank_logo_and_more'),
        ('orders', '0012_order_created_at_order_wallet_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orders.order', verbose_name='سفارش اصلی')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='accounts.provider', verbose_name='فروشنده')),
            ],
        ),
    ]
