# Generated by Django 5.2 on 2025-09-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_provider_vendororder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.vendororder'),
        ),
    ]
