# Generated by Django 5.2 on 2025-09-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_vendor_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendororder',
            options={'verbose_name': 'Vendor Order', 'verbose_name_plural': 'Vendor Orders'},
        ),
        migrations.AlterModelTable(
            name='vendororder',
            table='vendor_orders',
        ),
    ]
