# Generated by Django 5.2 on 2025-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_vendororder_options_alter_vendororder_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=10, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل'),
        ),
    ]
