# Generated by Django 5.2 on 2025-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد شدن'),
        ),
    ]
