# Generated by Django 5.2 on 2025-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_vendororder_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
