# Generated by Django 5.2 on 2025-09-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_vendororder_updated_at'),
        ('services', '0040_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.schedule', verbose_name='تاریخ رزرو'),
        ),
    ]
