# Generated by Django 5.2 on 2025-11-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Order Content',
                'verbose_name_plural': 'Order Contents',
                'db_table': 'order_contents',
            },
        ),
        migrations.CreateModel(
            name='OrderContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_contents/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.ordercontent')),
            ],
            options={
                'verbose_name': 'Order Content File',
                'verbose_name_plural': 'Order Contents Files',
                'db_table': 'order_content_files',
            },
        ),
    ]
